@ECHO OFF
rmdir /q /s MetX.Five\bin
rmdir /q /s MetX.Controls\bin
rmdir /q /s MetX.Glove.Console\bin
rmdir /q /s MetX\MetX.Console.Fimm\bin
rmdir /q /s MetX.Console.Research\bin
rmdir /q /s MetX.QuickScripts\bin
rmdir /q /s MetX.Standard.Primary\bin
rmdir /q /s MetX.Standard.Library\bin
rmdir /q /s MetX.Standard.Aspects\bin
rmdir /q /s MetX.Standard.Generators\bin
rmdir /q /s MetX.Standard.Generators.Aspects\bin
rmdir /q /s MetX.Standard.Generators.Support\bin
rmdir /q /s MetX.Standard.Generators.Actual\bin
rmdir /q /s MetX.Standard.Generators.Samples.Client\bin
rmdir /q /s MetX.Standard.XDString\bin
rmdir /q /s MetX.Techniques.Tests\bin
rmdir /q /s MetX.Tests\bin
rmdir /q /s MetX.Windows\bin

rmdir /q /s MetX.Five\obj
rmdir /q /s MetX.Aspects\obj
rmdir /q /s MetX.Controls\obj
rmdir /q /s MetX\MetX.Console.Fimm\obj
rmdir /q /s MetX.Console.Research\obj
rmdir /q /s MetX.Generators\obj
rmdir /q /s MetX.Glove.Console\obj
rmdir /q /s MetX.QuickScripts\obj
rmdir /q /s MetX.Standard.Primary\obj
rmdir /q /s MetX.Standard.Library\obj
rmdir /q /s MetX.Standard.Aspects\obj
rmdir /q /s MetX.Standard.Generators\obj
rmdir /q /s MetX.Standard.Generators.Aspects\obj
rmdir /q /s MetX.Standard.Generators.Support\obj
rmdir /q /s MetX.Standard.XDString\obj
rmdir /q /s MetX.Standard.Generators.Actual\obj
rmdir /q /s MetX.Standard.Generators.Samples.Client\obj
rmdir /q /s MetX.Techniques.Tests\obj
rmdir /q /s MetX.Tests\obj
rmdir /q /s MetX.Windows\obj