SELECT 
     KCU1.CONSTRAINT_NAME AS RelationshipName
    ,KCU1.TABLE_SCHEMA AS LeftSchema
    ,KCU1.TABLE_NAME AS LeftTable
    ,KCU1.COLUMN_NAME AS LeftColumn
    ,KCU1.ORDINAL_POSITION AS LeftPosition
    ,KCU2.TABLE_SCHEMA AS RightSchema
    ,KCU2.TABLE_NAME AS RightTable
    ,KCU2.COLUMN_NAME AS RightColumn
    ,KCU2.ORDINAL_POSITION AS RightPosition
    ,KCU2.CONSTRAINT_NAME AS RightKey
	,'Explicit' As RelationshipType
FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS AS RC
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU1 
		ON KCU1.CONSTRAINT_CATALOG = RC.CONSTRAINT_CATALOG  
		AND KCU1.CONSTRAINT_SCHEMA = RC.CONSTRAINT_SCHEMA 
		AND KCU1.CONSTRAINT_NAME = RC.CONSTRAINT_NAME 
	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE AS KCU2 
		ON KCU2.CONSTRAINT_CATALOG = RC.UNIQUE_CONSTRAINT_CATALOG  
		AND KCU2.CONSTRAINT_SCHEMA = RC.UNIQUE_CONSTRAINT_SCHEMA 
		AND KCU2.CONSTRAINT_NAME = RC.UNIQUE_CONSTRAINT_NAME 
		AND KCU2.ORDINAL_POSITION = KCU1.ORDINAL_POSITION 
ORDER BY 2,3,4,5,6,8,9

/*
SELECT
	Relationship = C.CONSTRAINT_NAME,
	LeftSchema = C.CONSTRAINT_SCHEMA,
	LeftTable = FK.TABLE_NAME,
	LeftColumn = CU.COLUMN_NAME,
	RightSchema = C.UNIQUE_CONSTRAINT_SCHEMA,
	RightTable = PK.TABLE_NAME,
	RightColumn = PT.COLUMN_NAME,
	Position = ORDINAL_POSITION
	FROM INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS C
		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS FK ON C.CONSTRAINT_NAME = FK.CONSTRAINT_NAME
		INNER JOIN INFORMATION_SCHEMA.TABLE_CONSTRAINTS PK ON C.UNIQUE_CONSTRAINT_NAME = PK.CONSTRAINT_NAME
		INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE CU ON C.CONSTRAINT_NAME = CU.CONSTRAINT_NAME
		INNER JOIN (
				SELECT i1.TABLE_NAME, i2.COLUMN_NAME 
					FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS i1
					INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE i2 ON i1.CONSTRAINT_NAME = i2.CONSTRAINT_NAME
					WHERE i1.CONSTRAINT_TYPE = 'PRIMARY KEY'
			) PT ON PT.TABLE_NAME = PK.TABLE_NAME
ORDER BY C.CONSTRAINT_NAME
--ORDER BY 2,3,4,5,6,7
*/